DefaultContentLanguage = 'es'
baseurl = "/"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm"]

[author]
    name = "Edwin & Nathalya"
    email = "nnnusechec@gmail.com"

[params]
    description = "Informational site about our wedding" # page description -> see ./layouts/partials/head.html
    images = [] #add images here as "img/name.ext" (points to s./static/img/) to populate the default og and twitter <meta> attributes -> see ./layouts/partials/head.html

[languages]
  [languages.ge]
    languageName = 'Deutsch'
    title = 'Meine Ehe - Edwin & Nathalya'
    weight = 1
    contentDir = 'content/german'

  [languages.es]
    languageName = 'Español'
    title = 'Mi boda - Edwin & Nathalya'
    weight = 2
    contentDir = 'content/spanish'

[[languages.ge.menu.main]]
    name = "heim"
    url = "/"
[[languages.es.menu.main]]
    name = "home"
    url = "/"
